// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgfwldsggwmmotafweki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnZndsZHNnZ3dtbW90YWZ3ZWtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NDg1MzAsImV4cCI6MjA3NDQyNDUzMH0.2Hk7k3WIGDidgpB4q945sVSjQWrljI7qrosC3KlMXKA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});